-- PROJECTS-SPR-602 migration (Founder Directive: Projects & Opportunities
-- Canonical Product) — creates the "ecosystems" table backing the new
-- Ecosystem CRUD in Admin, which now manages /portal/duan-cohoi (Canonical
-- Product) directly. Replaces the old digital_asset_projects/digital_asset_links
-- model (Consumer = 0 on the real Portal — only served the dead
-- /portal/digital-assets/** route).
--
-- QUAN TRỌNG: phải chạy script này trong Supabase SQL Editor TRƯỚC KHI merge
-- nhánh này vào Production. Nếu chưa chạy, /portal/duan-cohoi sẽ hiển thị
-- rỗng (bảng "ecosystems" chưa tồn tại → fetch API trả lỗi → Portal nhận
-- mảng rỗng, xem src/lib/admin/store.ts useSupabaseCollection). Nhánh này
-- chưa deploy Production (theo đúng "Không merge. Không deploy.").

create table if not exists ecosystems (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  status text not null default 'Draft',
  "order" int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table ecosystems enable row level security;
drop policy if exists "public read published" on ecosystems;
create policy "public read published" on ecosystems for select using (status in ('Published', 'Active'));

insert into ecosystems (id, data, status, "order") values
  ('eco_digiu', '{"id":"eco_digiu","slug":"digiu","articleCategory":"digiu","name":"Hệ sinh thái DigiU","icon":"layers","colorKey":"blue","shortDescription":"Nền tảng học và kiếm thu nhập số — mình đang đồng hành và chia sẻ trải nghiệm thực tế.","fullIntro":"DigiU là hệ sinh thái sản phẩm số mình đang trực tiếp đồng hành và quan sát, không phải một khoá học đã hoàn thiện. Trang này gom lại đúng những gì mình biết chắc tới hiện tại — không tô vẽ thêm để trông hấp dẫn hơn thực tế.","highlights":["Đang trong giai đoạn mình trực tiếp theo dõi và sử dụng, chưa phải đánh giá dài hạn.","Nội dung chia sẻ tại đây là trải nghiệm cá nhân, không phải tài liệu chính thức của DigiU."],"statusBadge":"Đang theo dõi","whoFor":"Người mới muốn bắt đầu kiếm thu nhập số, chấp nhận vài tháng đầu chưa có kết quả rõ ràng.","whoNotReady":"Người cần thu nhập ngay lập tức, hoặc chưa từng dùng công cụ AI cơ bản nào.","expectedOutcome":"Kỹ năng vận hành một kênh nội dung số bằng AI — không phải cam kết thu nhập cụ thể.","structureType":"sub-projects","links":[{"id":"link_digiu_main","label":"Đăng ký / đăng nhập DigiU","url":"https://lk.digiu.ai/auth/registration/6845205668","order":1,"visible":true}],"subProjects":[{"id":"sub_digiu_alphamind","slug":"alphamind","name":"Khoá học Alphamind","shortDescription":"Một sản phẩm học trong hệ sinh thái DigiU — đăng ký qua cùng cổng tài khoản DigiU.","colorIndex":0,"links":[{"id":"link_alphamind","label":"Đăng ký Khoá học Alphamind","url":"https://lk.digiu.ai/auth/registration/6845205668","order":1,"visible":true}]},{"id":"sub_digiu_webwisepay","slug":"webwisepay","name":"Mở thẻ WebWisePay","shortDescription":"Sản phẩm thẻ trong hệ sinh thái DigiU — đăng ký qua Telegram bot riêng.","colorIndex":1,"links":[{"id":"link_webwisepay","label":"Mở thẻ WebWisePay (Telegram)","url":"https://t.me/WebWisePay_bot?start=ref_49419218-1eac-4683-ab3e-74a7ca266da0","order":1,"visible":true}]},{"id":"sub_digiu_deposits","slug":"deposits","name":"Mở khoản tiền gửi (Deposits)","shortDescription":"Sản phẩm tiền gửi trong hệ sinh thái DigiU — đăng ký qua cùng cổng tài khoản DigiU.","colorIndex":2,"links":[{"id":"link_deposits","label":"Mở khoản tiền gửi (Deposits)","url":"https://lk.digiu.ai/auth/registration/6845205668","order":1,"visible":true}]}],"faq":[],"relatedArticleIds":["daa_1","daa_2"],"order":1,"status":"Published"}'::jsonb, 'Published', 1),
  ('eco_solargroup', '{"id":"eco_solargroup","slug":"solargroup","articleCategory":"equity","name":"SolarGroup","icon":"building","colorKey":"amber","shortDescription":"Cơ hội đầu tư cổ phần dài hạn — mình đang nghiên cứu và chia sẻ góc nhìn cá nhân.","fullIntro":"SolarGroup là một mô hình cổ phần dài hạn mình đang tìm hiểu, chưa phải thứ mình đã tham gia đủ lâu để khẳng định chắc chắn điều gì. Trang này trình bày đúng những gì mình đã đọc/quan sát được, cùng phần mình chưa chắc chắn.","highlights":["Đang ở giai đoạn nghiên cứu — mình chưa coi đây là khuyến nghị tham gia.","Mô hình đòi hỏi vốn để lâu dài, không phù hợp cho nhu cầu thanh khoản ngắn hạn."],"statusBadge":"Đang nghiên cứu","whoFor":"Người có vốn nhàn rỗi thật sự sẵn sàng để lâu dài, chấp nhận không rút được ngay khi cần.","whoNotReady":"Người cần thanh khoản ngắn hạn, hoặc chưa từng đọc một bản cáo bạch/whitepaper đầu tư nào.","expectedOutcome":"Hiểu rõ hơn cách một mô hình cổ phần dài hạn vận hành — không phải cam kết lợi nhuận.","structureType":"sub-projects","links":[{"id":"link_solargroup_main","label":"Đăng ký / xem trạng thái SolarGroup","url":"https://reg.solargroup.pro/vi/user/ref/plan/my-status?ref_code=frp116","order":1,"visible":true}],"subProjects":[{"id":"sub_solargroup_sovelmash","slug":"sovelmash","name":"Nhà máy Sovelmash","shortDescription":"Một dự án con trong hệ sinh thái SolarGroup — đăng ký qua link riêng của dự án.","colorIndex":0,"links":[{"id":"link_sovelmash","label":"Xem dự án Nhà máy Sovelmash","url":"https://reg.solargroup.pro/frp116/solargroup","order":1,"visible":true}]},{"id":"sub_solargroup_aeronova","slug":"aeronova","name":"Dự án Khí cầu thế hệ mới AERONOVA","shortDescription":"Một dự án con trong hệ sinh thái SolarGroup — đăng ký qua link riêng của dự án.","colorIndex":1,"links":[{"id":"link_aeronova","label":"Xem dự án Khí cầu AERONOVA","url":"https://reg.solargroup.pro/frp116/airships","order":1,"visible":true}]}],"faq":[],"relatedArticleIds":["daa_6"],"order":2,"status":"Published"}'::jsonb, 'Published', 2),
  ('eco_crypto', '{"id":"eco_crypto","slug":"blockchain-crypto","articleCategory":"crypto","extraArticleCategories":["blockchain"],"name":"Blockchain & Crypto","icon":"bitcoin","colorKey":"slate-emerald","shortDescription":"Kiến thức nền tảng về hai mảng Blockchain và Crypto — bao gồm cả bài học từ sai lầm.","fullIntro":"Đây là nơi mình gom lại kiến thức nền về blockchain và crypto — hai mảng khác nhau nhưng liên quan chặt chẽ. Mục tiêu là giúp bạn hiểu đúng phạm vi từng mảng trước khi tự mình tìm hiểu sâu hơn, không phải để bạn làm theo một chiến lược cụ thể nào.","highlights":["Bao gồm cả bài học từ những lần mình từng mất tiền hoặc thao tác sai.","Biến động giá và rủi ro công nghệ ở đây cao hơn nhiều so với các hệ sinh thái khác trên trang."],"statusBadge":"Chia sẻ trải nghiệm","whoFor":"Người tò mò về công nghệ mới, chấp nhận rủi ro cao và biến động giá lớn.","whoNotReady":"Người chưa từng tự quản lý một ví số, hoặc coi đây là cách làm giàu nhanh.","expectedOutcome":"Kiến thức nền về blockchain/crypto và cách tự bảo vệ tài sản số — không phải lợi nhuận giao dịch.","structureType":"two-field","links":[],"fields":[{"id":"field_blockchain","name":"Blockchain","description":"Mảng công nghệ nền: cách một sổ cái phân tán vận hành, các loại nền tảng blockchain, ví và hợp đồng thông minh. Đây là kiến thức nền, không phải danh sách dự án cụ thể để tham gia.","links":[]},{"id":"field_crypto","name":"Crypto","description":"Mảng tài sản số xây dựng trên nền blockchain: cách thị trường vận hành, cách tự quản lý và bảo vệ tài sản, cùng rủi ro biến động giá. Đây là kiến thức nền, không phải tín hiệu mua/bán.","links":[]}],"faq":[],"relatedArticleIds":[],"order":3,"status":"Published"}'::jsonb, 'Published', 3),
  ('eco_blockchain', '{"id":"eco_blockchain","slug":"lam-affilate","articleCategory":"blockchain","name":"Làm tiếp thị liên kết (Affiliate)","icon":"link","colorKey":"violet-blue","shortDescription":"Nơi mình liệt kê các chương trình/khoá học tiếp thị liên kết đang tìm hiểu hoặc quảng bá.","fullIntro":"Đây là nơi mình liệt kê các chương trình tiếp thị liên kết (affiliate) thật — sàn thương mại điện tử, khoá học — mà mình đang tìm hiểu hoặc quảng bá. Danh sách này có thể thêm/bớt theo thời gian; mục nào chưa có link tiếp thị thật sẽ ghi rõ thay vì dùng link giả.","highlights":["Danh sách có thể thêm/bớt theo thời gian, không phải danh sách cố định.","Mục nào chưa có link tiếp thị thật sẽ ghi rõ ''chưa có link'' thay vì dùng link giả."],"statusBadge":"Đang theo dõi","whoFor":"Người muốn tìm hiểu các chương trình tiếp thị liên kết cụ thể mình đang theo dõi.","whoNotReady":"Người tìm kiếm một danh sách link tiếp thị đã có sẵn và hoạt động ngay hôm nay.","expectedOutcome":"Biết rõ những chương trình affiliate mình đang tìm hiểu — không phải cam kết thu nhập.","structureType":"affiliate-list","links":[{"id":"aff_lazada","label":"Lazada","url":"","category":"Sàn TMĐT","order":1,"visible":true},{"id":"aff_shopee","label":"Shopee","url":"","category":"Sàn TMĐT","order":2,"visible":true},{"id":"aff_unica","label":"Unica (khoá học)","url":"","category":"Khoá học","order":3,"visible":true},{"id":"aff_khoi_nguyen_mmo","label":"Khởi Nguyên MMO (khoá học)","url":"","category":"Khoá học","order":4,"visible":true}],"faq":[],"relatedArticleIds":[],"order":4,"status":"Published"}'::jsonb, 'Published', 4),
  ('eco_trading', '{"id":"eco_trading","slug":"sangiaodich","articleCategory":"trading","name":"Các sàn giao dịch Crypto","icon":"chart","colorKey":"emerald-green","shortDescription":"Danh sách các sàn giao dịch crypto mình đang theo dõi hoặc đã dùng thử.","fullIntro":"Đây là danh sách các sàn giao dịch crypto thật, có thể thêm/bớt theo thời gian. Sàn nào chưa có link tiếp thị thật của mình sẽ ghi rõ thay vì dùng link giả — tự bạn vẫn nên vào trang chính thức của từng sàn để tìm hiểu kỹ trước khi dùng.","highlights":["Danh sách có thể thêm/bớt theo thời gian, không phải một bảng xếp hạng ''tốt nhất''.","Sàn nào chưa có link tiếp thị thật sẽ ghi rõ ''chưa có link'' thay vì dùng link giả."],"statusBadge":"Chia sẻ kiến thức","whoFor":"Người đã hiểu kiến thức nền về crypto, muốn biết các sàn giao dịch cụ thể mình đang theo dõi.","whoNotReady":"Người chưa hiểu kiến thức nền về crypto/ví số — nên đọc Blockchain & Crypto trước.","expectedOutcome":"Biết rõ các sàn giao dịch mình đang theo dõi/đã dùng — không phải khuyến nghị nên chọn sàn nào.","structureType":"exchange-list","links":[{"id":"exc_binance","label":"Binance","url":"","order":1,"visible":true},{"id":"exc_okx","label":"OKX","url":"","order":2,"visible":true},{"id":"exc_mexc","label":"MEXC","url":"","order":3,"visible":true},{"id":"exc_bybit","label":"Bybit","url":"","order":4,"visible":true},{"id":"exc_kucoin","label":"Kucoin","url":"","order":5,"visible":true},{"id":"exc_gate","label":"Gate","url":"","order":6,"visible":true},{"id":"exc_bitget","label":"Bitget","url":"","order":7,"visible":true}],"faq":[],"relatedArticleIds":[],"order":5,"status":"Published"}'::jsonb, 'Published', 5)
on conflict (id) do nothing;
