/**
 * Companion Orchestration System™ — Agent Registry (Product Amendment 02).
 * Danh sách đầy đủ đội ngũ chuyên gia phía sau Companion, theo từng module
 * Portal. Đây là dữ liệu nội bộ Companion dùng để lập kế hoạch — không
 * render trực tiếp thành menu/trang cho người dùng.
 */

import type { CompanionAgent } from "./agent.types";

export const AGENT_REGISTRY: CompanionAgent[] = [
  // 1. Không gian AI — thử AI, đặt câu hỏi tốt hơn, chọn công cụ, thực hành.
  {
    id: "prompt-coach",
    name: "AI Prompt Coach",
    role: "Giúp người dùng đặt câu hỏi/prompt tốt hơn",
    module: "khong-gian-ai",
    capabilities: ["Gợi ý cách diễn đạt prompt rõ ràng hơn", "Chỉ ra thiếu sót trong câu hỏi"],
    triggerContext: ["Người dùng mới thử AI", "Prompt còn mơ hồ"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "idea-partner",
    name: "AI Idea Partner",
    role: "Cùng brainstorm ý tưởng ban đầu",
    module: "khong-gian-ai",
    capabilities: ["Gợi mở hướng thử nghiệm", "Đưa ví dụ ý tưởng liên quan"],
    triggerContext: ["Người dùng chưa biết bắt đầu từ đâu"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "tool-guide",
    name: "AI Tool Guide",
    role: "Chọn công cụ AI phù hợp với nhu cầu",
    module: "khong-gian-ai",
    capabilities: ["So sánh công cụ theo mục tiêu", "Hướng dẫn bắt đầu với 1 công cụ"],
    triggerContext: ["Người dùng phân vân chọn công cụ nào"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "practice-helper",
    name: "AI Practice Helper",
    role: "Hỗ trợ bước thực hành đầu tiên",
    module: "khong-gian-ai",
    capabilities: ["Gợi ý bài tập nhỏ để thử ngay", "Theo sát bước thực hành"],
    triggerContext: ["Người dùng đã chọn công cụ, cần thử ngay"],
    outputType: "guidance",
    status: "planned",
  },

  // 2. Thư viện tri thức / CKOS — hiểu tri thức, tóm tắt Seed, gợi ý prompt.
  {
    id: "research",
    name: "AI Research Agent",
    role: "Tìm và tổng hợp thông tin nền cho một chủ đề",
    module: "ckos",
    capabilities: ["Tổng hợp nguồn liên quan", "Giải thích bối cảnh chủ đề"],
    triggerContext: ["Người dùng cần hiểu sâu một Knowledge Seed"],
    outputType: "summary",
    status: "planned",
  },
  {
    id: "ckos-writer",
    name: "AI Writer Agent",
    role: "Diễn giải tri thức thành nội dung dễ hiểu",
    module: "ckos",
    capabilities: ["Viết lại khái niệm bằng ngôn ngữ đơn giản", "Tạo ví dụ minh hoạ"],
    triggerContext: ["Seed tri thức khó hiểu với người mới"],
    outputType: "content",
    status: "planned",
  },
  {
    id: "ckos-prompt-agent",
    name: "AI Prompt Agent",
    role: "Gợi ý prompt để thực hành với Seed vừa học",
    module: "ckos",
    capabilities: ["Sinh prompt thực hành theo Seed", "Điều chỉnh độ khó prompt"],
    triggerContext: ["Người dùng vừa học xong một Seed"],
    outputType: "content",
    status: "planned",
  },
  {
    id: "ckos-reviewer",
    name: "AI Reviewer Agent",
    role: "Kiểm tra và góp ý kết quả thực hành",
    module: "ckos",
    capabilities: ["Đối chiếu kết quả với mục tiêu Seed", "Đưa góp ý cải thiện"],
    triggerContext: ["Người dùng đã thử áp dụng Seed"],
    outputType: "analysis",
    status: "planned",
  },
  {
    id: "ckos-summary",
    name: "AI Summary Agent",
    role: "Tóm tắt Seed/Collection tri thức",
    module: "ckos",
    capabilities: ["Tóm tắt ngắn gọn nội dung dài", "Nêu ý chính cần nhớ"],
    triggerContext: ["Người dùng muốn ôn nhanh trước khi tiếp tục"],
    outputType: "summary",
    status: "planned",
  },

  // 3. Học viện / Academy — học – làm thật, Mission, Evidence, Reflection, Growth.
  {
    id: "mission-planner",
    name: "AI Mission Planner",
    role: "Chia nhỏ một Mission thành các bước làm được",
    module: "academy",
    capabilities: ["Phân rã Mission thành bước rõ ràng", "Ước lượng Agent cần mời cho từng bước"],
    triggerContext: ["Người dùng bắt đầu một Mission mới"],
    outputType: "plan",
    status: "planned",
  },
  {
    id: "practice-coach",
    name: "AI Practice Coach",
    role: "Đồng hành khi người dùng đang làm Mission",
    module: "academy",
    capabilities: ["Gợi ý cách vượt qua bước khó", "Khuyến khích khi người dùng chững lại"],
    triggerContext: ["Người dùng đang thực hành giữa chừng Mission"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "evidence-helper",
    name: "AI Evidence Helper",
    role: "Giúp ghi lại minh chứng đã hoàn thành",
    module: "academy",
    capabilities: ["Gợi ý cách trình bày Evidence", "Kiểm tra Evidence đủ rõ ràng chưa"],
    triggerContext: ["Người dùng hoàn thành một bước cần ghi minh chứng"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "reflection-partner",
    name: "AI Reflection Partner",
    role: "Đặt câu hỏi Reflection sau Mission",
    module: "academy",
    capabilities: ["Gợi câu hỏi suy ngẫm phù hợp", "Giúp diễn đạt điều đã học"],
    triggerContext: ["Người dùng vừa hoàn thành Mission"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "growth-reviewer",
    name: "AI Growth Reviewer",
    role: "Nhận định sự trưởng thành sau Mission",
    module: "academy",
    capabilities: ["So sánh trước/sau Mission", "Chỉ ra điều đã thay đổi thật"],
    triggerContext: ["Kết thúc một Mission hoặc một chuỗi Mission"],
    outputType: "analysis",
    status: "planned",
  },

  // 4. Dự án & Cơ hội — áp dụng vào dự án thật, phân tích cơ hội/rủi ro.
  {
    id: "project-analyst",
    name: "AI Project Analyst",
    role: "Phân tích tình trạng và tiềm năng của một dự án",
    module: "opportunities",
    capabilities: ["Đánh giá dự án theo tiêu chí rõ ràng", "Chỉ ra điểm mạnh/điểm thiếu"],
    triggerContext: ["Người dùng muốn hiểu rõ hơn một dự án cụ thể"],
    outputType: "analysis",
    status: "planned",
  },
  {
    id: "risk-analyst",
    name: "AI Risk Analyst",
    role: "Nhận diện rủi ro trước khi hành động",
    module: "opportunities",
    capabilities: ["Liệt kê rủi ro có thể gặp", "Gợi ý cách giảm thiểu"],
    triggerContext: ["Người dùng chuẩn bị đầu tư thời gian/tiền vào cơ hội"],
    outputType: "analysis",
    status: "planned",
  },
  {
    id: "strategy-agent",
    name: "AI Strategy Agent",
    role: "Gợi ý hướng tiếp cận chiến lược",
    module: "opportunities",
    capabilities: ["Đề xuất hướng đi phù hợp năng lực hiện tại", "So sánh phương án"],
    triggerContext: ["Người dùng cần chọn hướng đi cho dự án"],
    outputType: "plan",
    status: "planned",
  },
  {
    id: "opportunity-mapper",
    name: "AI Opportunity Mapper",
    role: "Vẽ bản đồ cơ hội phù hợp với người dùng",
    module: "opportunities",
    capabilities: ["Gợi ý cơ hội khớp với năng lực/mục tiêu", "Sắp xếp cơ hội theo độ ưu tiên"],
    triggerContext: ["Người dùng muốn tìm cơ hội mới để áp dụng"],
    outputType: "analysis",
    status: "planned",
  },
  {
    id: "action-planner",
    name: "AI Action Planner",
    role: "Lập kế hoạch hành động cụ thể",
    module: "opportunities",
    capabilities: ["Chuyển ý tưởng thành các bước hành động", "Đặt mốc thời gian gợi ý"],
    triggerContext: ["Người dùng đã chọn hướng đi, cần kế hoạch"],
    outputType: "plan",
    status: "planned",
  },

  // 5. Premium — đồng hành sâu hơn, thực hành nâng cao, cá nhân hoá.
  {
    id: "deep-mentor",
    name: "AI Deep Mentor",
    role: "Đồng hành ở mức sâu hơn cho vấn đề phức tạp",
    module: "premium",
    capabilities: ["Phân tích vấn đề nhiều lớp", "Đưa góc nhìn nâng cao"],
    triggerContext: ["Người dùng Premium cần đi sâu hơn mức cơ bản"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "advanced-strategy",
    name: "AI Advanced Strategy Agent",
    role: "Chiến lược nâng cao cho người đã có nền tảng",
    module: "premium",
    capabilities: ["Đề xuất chiến lược phức hợp", "Cân nhắc nhiều biến số cùng lúc"],
    triggerContext: ["Người dùng đã vững nền tảng, cần chiến lược cao hơn"],
    outputType: "plan",
    status: "planned",
  },
  {
    id: "case-study-agent",
    name: "AI Case Study Agent",
    role: "Đối chiếu tình huống người dùng với case study thật",
    module: "premium",
    capabilities: ["Tìm case study liên quan", "Rút bài học áp dụng được"],
    triggerContext: ["Người dùng muốn học từ ví dụ thực tế tương tự"],
    outputType: "summary",
    status: "planned",
  },
  {
    id: "personal-growth-coach",
    name: "AI Personal Growth Coach",
    role: "Định hướng phát triển cá nhân hoá",
    module: "premium",
    capabilities: ["Gợi ý hướng phát triển riêng cho người dùng", "Theo sát mục tiêu dài hạn"],
    triggerContext: ["Người dùng cần định hướng cá nhân hoá hơn"],
    outputType: "guidance",
    status: "planned",
  },

  // 6. Nhật ký học tập — Reflection, KHÔNG để Agent xuất hiện trực tiếp.
  {
    id: "reflection-helper",
    name: "AI Reflection Helper",
    role: "Giúp diễn đạt điều vừa trải nghiệm",
    module: "learning-journal",
    capabilities: ["Gợi ý câu hỏi phản tư", "Giúp bắt đầu viết Reflection"],
    triggerContext: ["Người dùng chưa biết bắt đầu viết gì"],
    outputType: "guidance",
    status: "planned",
  },
  {
    id: "insight-extractor",
    name: "AI Insight Extractor",
    role: "Rút ra bài học từ Reflection đã viết",
    module: "learning-journal",
    capabilities: ["Chỉ ra ý chính trong Reflection", "Kết nối Reflection với Mission liên quan"],
    triggerContext: ["Người dùng vừa viết xong một Reflection"],
    outputType: "summary",
    status: "planned",
  },
  {
    id: "learning-summary",
    name: "AI Learning Summary Agent",
    role: "Tổng hợp những gì đã học qua nhiều Reflection",
    module: "learning-journal",
    capabilities: ["Tổng hợp theo tuần/tháng", "Nêu chủ đề lặp lại"],
    triggerContext: ["Người dùng muốn nhìn lại một giai đoạn học"],
    outputType: "summary",
    status: "planned",
  },

  // 7. Hành trình của tôi — nhìn lại câu chuyện trưởng thành.
  {
    id: "journey-narrator",
    name: "AI Journey Narrator",
    role: "Kể lại hành trình như một câu chuyện",
    module: "my-journey",
    capabilities: ["Ghép các mốc thành mạch câu chuyện", "Nhấn vào khoảnh khắc ý nghĩa"],
    triggerContext: ["Người dùng xem lại toàn bộ hành trình"],
    outputType: "narrative",
    status: "planned",
  },
  {
    id: "progress-interpreter",
    name: "AI Progress Interpreter",
    role: "Diễn giải ý nghĩa của tiến trình",
    module: "my-journey",
    capabilities: ["Giải thích vì sao một giai đoạn quan trọng", "So sánh giai đoạn trước/sau"],
    triggerContext: ["Người dùng muốn hiểu ý nghĩa tiến trình, không chỉ con số"],
    outputType: "analysis",
    status: "planned",
  },
  {
    id: "growth-story-agent",
    name: "AI Growth Story Agent",
    role: "Ghi nhận câu chuyện trưởng thành cụ thể",
    module: "my-journey",
    capabilities: ["Chọn ra khoảnh khắc trưởng thành đáng nhớ", "Diễn đạt thành câu chuyện ngắn"],
    triggerContext: ["Người dùng đạt một cột mốc trưởng thành"],
    outputType: "narrative",
    status: "planned",
  },

  // 8. Khu vườn của bạn — ý nghĩa sự trưởng thành trong khu vườn.
  {
    id: "growth-visualizer",
    name: "AI Growth Visualizer",
    role: "Giải thích hình ảnh khu vườn phản ánh điều gì",
    module: "living-garden",
    capabilities: ["Diễn giải trạng thái cây theo hành động thật", "Kết nối hình ảnh với dữ liệu trưởng thành"],
    triggerContext: ["Người dùng xem khu vườn và chưa rõ ý nghĩa"],
    outputType: "visualization",
    status: "planned",
  },
  {
    id: "garden-interpreter",
    name: "AI Garden Interpreter",
    role: "Diễn giải ý nghĩa từng giai đoạn khu vườn",
    module: "living-garden",
    capabilities: ["Giải thích giai đoạn hiện tại của khu vườn", "Nêu điều đã góp phần làm vườn lớn lên"],
    triggerContext: ["Khu vườn vừa chuyển sang giai đoạn mới"],
    outputType: "narrative",
    status: "planned",
  },
  {
    id: "next-growth-agent",
    name: "AI Next Growth Agent",
    role: "Gợi ý bước trưởng thành tiếp theo",
    module: "living-garden",
    capabilities: ["Gợi ý hành động nhỏ tiếp theo", "Kết nối tới Mission/Reflection phù hợp"],
    triggerContext: ["Người dùng muốn biết nên làm gì tiếp theo"],
    outputType: "plan",
    status: "planned",
  },
];

export function getAgentById(id: string): CompanionAgent | undefined {
  return AGENT_REGISTRY.find((agent) => agent.id === id);
}

export function getAgentsByModule(module: CompanionAgent["module"]): CompanionAgent[] {
  return AGENT_REGISTRY.filter((agent) => agent.module === module);
}
