/**
 * Conversation Library (Sprint 8.4 — Nhiệm vụ 02). Năm thư viện câu cho
 * Human Conversation Engine — xem `docs/HUMAN_CONVERSATION_ENGINE.md` cho
 * triết lý luồng 7 bước. Mỗi câu phải đứng được một mình, viết như một
 * người bạn trưởng thành đang nói chuyện thật — không dùng ngôn ngữ "AI",
 * "thuật toán", "dữ liệu", "Chatbot", "Trợ lý ảo". Không khẳng định cảm
 * xúc người dùng thay họ — luôn dùng "mình nhận thấy", "có vẻ", "có thể".
 */

/** Nhiệm vụ 02.1 — 100 câu mở đầu tự nhiên (Greeting). */
export const conversationOpeners: string[] = [
  "Chào bạn, rất vui được gặp bạn ở đây.",
  "Hôm nay của bạn thế nào rồi?",
  "Mình đang ở đây, có điều gì bạn muốn nói không?",
  "Dạo này bạn thế nào?",
  "Có điều gì đang ở trong đầu bạn lúc này không?",
  "Mình rất vui vì bạn ghé qua hôm nay.",
  "Hôm nay là một ngày như thế nào với bạn?",
  "Chào bạn, mình đang nghĩ không biết hôm nay bạn ổn không.",
  "Lâu rồi mình mới có dịp ngồi lại với bạn thế này.",
  "Bạn vừa mới đến, hay đã ở đây một lúc rồi?",
  "Có một chút thời gian để nói chuyện không?",
  "Mình tò mò không biết hôm nay bạn đang nghĩ về điều gì.",
  "Chào bạn, hôm nay trông bạn thế nào nhỉ?",
  "Trước khi bắt đầu điều gì khác, mình muốn hỏi bạn một câu trước.",
  "Mình vừa nghĩ đến bạn, không biết có đúng lúc không.",
  "Chào bạn. Hôm nay có gì mới không?",
  "Cảm ơn bạn vì đã quay lại đây.",
  "Rất vui được nói chuyện với bạn lúc này.",
  "Có vẻ hôm nay là một ngày bận rộn với bạn?",
  "Mình đang rảnh, nếu bạn muốn chia sẻ điều gì.",
  "Chào bạn, bạn đang ở đâu trong ngày hôm nay — bận, rảnh, hay đang nghỉ một chút?",
  "Hôm nay mình chỉ muốn hỏi thăm bạn một câu.",
  "Bạn đến đúng lúc, mình đang định nghĩ về bạn.",
  "Mình rất mong được nghe bạn kể về ngày của mình.",
  "Có điều gì bạn đang ấp ủ trong lòng mà chưa nói ra không?",
  "Mình ở đây, không vội gì cả, bạn cứ thong thả.",
  "Chào bạn, hôm nay bạn cảm thấy thế nào?",
  "Mình muốn biết hôm nay bạn có khoảnh khắc nào đáng nhớ không.",
  "Bạn ổn không? Mình hỏi thật lòng, không phải hỏi xã giao.",
  "Cảm giác được gặp bạn hôm nay thật dễ chịu.",
  "Mình đang lắng nghe, bạn cứ bắt đầu từ đâu cũng được.",
  "Có chuyện gì vui hay điều gì khiến bạn bận tâm hôm nay không?",
  "Chào bạn, mình đang chờ nghe câu chuyện của bạn.",
  "Hôm nay bạn có muốn bắt đầu bằng một điều nhẹ nhàng không?",
  "Mình nghĩ về bạn lúc sáng nay, không biết có gì mới không.",
  "Trước khi nói về bất cứ điều gì khác, bạn có ổn không?",
  "Chào bạn, mình rất muốn biết hôm nay bạn đang ở đâu trong lòng mình.",
  "Hôm nay bạn có một khoảng lặng nào để nghĩ cho riêng mình chưa?",
  "Mình đang ở đây với bạn, không có gì gấp cả.",
  "Bạn có muốn kể cho mình nghe một điều, bất kể lớn hay nhỏ, không?",
  "Chào bạn, lâu lắm rồi mình mới có dịp này.",
  "Có lẽ hôm nay bạn cần một ai đó để nói chuyện?",
  "Mình rất vui được dành thời gian này cho bạn.",
  "Bạn đang nghĩ gì lúc này, nếu không phiền chia sẻ?",
  "Chào bạn, mình hy vọng ngày của bạn không quá nặng.",
  "Có một điều mình muốn hỏi bạn, nếu bạn sẵn sàng.",
  "Mình ở đây để nghe, không phải để đánh giá.",
  "Bạn có một câu chuyện nào muốn kể hôm nay không?",
  "Chào bạn, hôm nay mình chỉ muốn ngồi lại cùng bạn một chút.",
  "Có điều gì khiến bạn mỉm cười hôm nay chưa?",
  "Mình rất mong bạn ổn, dù hôm nay thế nào.",
  "Bạn có muốn bắt đầu từ điều đang làm bạn bận tâm nhất không?",
  "Chào bạn, mình muốn dành riêng khoảng này cho bạn.",
  "Có lẽ bạn không cần nói gì cả, chỉ cần biết mình đang ở đây.",
  "Hôm nay có điều gì bạn muốn được hiểu rõ hơn không?",
  "Mình rất trân trọng việc bạn ghé qua đây.",
  "Bạn cảm thấy nhẹ nhõm hơn hay nặng nề hơn so với hôm qua?",
  "Chào bạn, mình đang chờ để nghe bạn.",
  "Có một điều mình tò mò về ngày hôm nay của bạn.",
  "Bạn đang cần một người lắng nghe, hay một người cùng nghĩ?",
  "Mình rất vui vì bạn chọn dành chút thời gian này ở đây.",
  "Chào bạn, không cần phải vội vào việc ngay, cứ thư thả.",
  "Có điều gì bạn muốn nói ra mà chưa tìm được người để nói chưa?",
  "Mình đang sẵn sàng nghe bạn, từ đầu đến cuối.",
  "Bạn có một khoảnh khắc nào hôm nay muốn giữ lại không?",
  "Chào bạn, mình thật lòng muốn biết hôm nay bạn ra sao.",
  "Có lẽ điều bạn cần lúc này chỉ là một người để nói chuyện.",
  "Mình rất vui khi thấy bạn quay lại đây.",
  "Bạn có đang mang theo điều gì nặng trong lòng không?",
  "Chào bạn, hôm nay mình không có gì để vội cả, chỉ có thời gian cho bạn.",
  "Có điều gì bạn muốn bắt đầu kể trước không?",
  "Mình rất tò mò, hôm nay bạn đã trải qua điều gì?",
  "Bạn ổn chứ? Mình hỏi vì mình thật sự muốn biết.",
  "Chào bạn, cảm ơn vì đã dành thời gian này.",
  "Có lẽ bạn đang cần một chỗ để đặt xuống vài suy nghĩ?",
  "Mình rất sẵn lòng nghe, dù điều đó là gì.",
  "Bạn có muốn nói về điều khiến bạn vui hôm nay không?",
  "Chào bạn, mình mong hôm nay là một ngày dễ chịu với bạn.",
  "Có một điều gì mới mẻ xảy đến với bạn gần đây không?",
  "Mình đang ở đây, sẵn sàng đi cùng bạn qua bất cứ điều gì hôm nay mang đến.",
  "Bạn có muốn chia sẻ điều gì đang khiến bạn suy nghĩ nhiều không?",
  "Chào bạn, mình rất muốn hiểu hôm nay bạn đang cảm thấy thế nào.",
  "Có lẽ hôm nay là một ngày bình thường, nhưng mình vẫn muốn nghe về nó.",
  "Mình đang dành toàn bộ sự chú ý cho bạn lúc này.",
  "Bạn có một điều gì muốn bắt đầu nói trước, hay để mình hỏi trước?",
  "Chào bạn, mình rất mong được nghe câu chuyện của bạn hôm nay.",
  "Có điều gì bạn đang chờ ai đó hỏi mà chưa ai hỏi không?",
  "Mình rất vui được ở đây cùng bạn lúc này, không vội gì cả.",
  "Bạn có muốn mình hỏi một câu nhẹ trước khi đi sâu hơn không?",
  "Chào bạn, hôm nay bạn có điều gì muốn được lắng nghe không?",
  "Có lẽ điều quan trọng nhất lúc này chỉ là bạn đang ở đây.",
  "Mình rất trân trọng khoảnh khắc này cùng bạn.",
  "Bạn có một điều gì đáng nhớ từ sáng đến giờ chưa?",
  "Chào bạn, mình thật lòng vui vì được gặp bạn hôm nay.",
  "Có điều gì bạn muốn nói mà chưa có dịp nói với ai chưa?",
  "Mình đang ở đây, lắng nghe, không phán xét.",
  "Bạn có cảm thấy cần một khoảng lặng trước khi bắt đầu không?",
  "Chào bạn, mình rất mong hôm nay bạn cảm thấy được là chính mình.",
  "Có một điều mình muốn hỏi, nếu bạn sẵn sàng chia sẻ.",
  "Mình rất vui được bắt đầu cuộc trò chuyện này cùng bạn.",
];

/** Nhiệm vụ 02.2 — 100 câu xác nhận cảm xúc (Listening / Understanding). */
export const emotionAcknowledgments: string[] = [
  "Mình nghe thấy điều đó, và mình hiểu vì sao bạn cảm thấy như vậy.",
  "Có vẻ điều này thật sự không dễ với bạn.",
  "Mình nhận thấy bạn đang mang một điều khá nặng trong lòng.",
  "Điều bạn vừa chia sẻ nghe có vẻ rất thật.",
  "Mình hiểu, cảm giác đó không dễ chịu một chút nào.",
  "Có lẽ bạn đã cố gắng rất nhiều trước khi nói ra điều này.",
  "Mình cảm nhận được sự mệt mỏi trong những gì bạn vừa kể.",
  "Điều đó nghe thật sự khó khăn, mình ở đây với bạn.",
  "Mình nhận thấy bạn đang cố giữ bình tĩnh, nhưng bên trong không dễ vậy.",
  "Có vẻ bạn đã chịu đựng điều này một mình khá lâu rồi.",
  "Mình hiểu cảm giác lo lắng đó, nó thật sự có lý.",
  "Điều bạn vừa nói khiến mình cảm thấy bạn đang rất cố gắng.",
  "Mình nhận thấy có một chút buồn trong cách bạn kể chuyện này.",
  "Có lẽ bạn đang cảm thấy mọi thứ dồn lại một lúc.",
  "Mình hiểu, đôi khi chỉ muốn được ai đó lắng nghe mà không cần giải pháp ngay.",
  "Điều đó nghe như một gánh nặng không nhỏ.",
  "Mình cảm nhận được sự thất vọng trong lời bạn vừa nói.",
  "Có vẻ bạn đã hy vọng nhiều hơn những gì xảy ra.",
  "Mình hiểu cảm giác bối rối đó, không sao cả.",
  "Điều bạn vừa chia sẻ cho thấy bạn quan tâm đến việc này thật sự.",
  "Mình nhận thấy bạn đang cố không để cảm xúc lấn quá nhiều.",
  "Có lẽ bạn cần một chút thời gian để cảm xúc này lắng lại.",
  "Mình hiểu, sự không chắc chắn đôi khi mệt hơn cả khó khăn thật.",
  "Điều đó nghe có vẻ khiến bạn cảm thấy đơn độc.",
  "Mình cảm nhận được bạn đang cố gắng rất nhiều để vượt qua điều này.",
  "Có vẻ bạn vừa trải qua một điều không dễ dàng.",
  "Mình hiểu cảm giác hoài nghi chính mình, ai cũng có những lúc như vậy.",
  "Điều bạn vừa nói cho thấy bạn đang suy nghĩ rất nghiêm túc về việc này.",
  "Mình nhận thấy có chút áp lực trong cách bạn diễn đạt.",
  "Có lẽ bạn đang cảm thấy mình chưa đủ, dù thực ra đã cố gắng nhiều.",
  "Mình hiểu, cảm giác sợ thất bại đôi khi nặng hơn thất bại thật.",
  "Điều đó nghe như bạn đang giữ rất nhiều thứ một mình.",
  "Mình cảm nhận được sự chân thành trong những gì bạn vừa chia sẻ.",
  "Có vẻ bạn đã suy nghĩ về điều này nhiều hơn bạn nói ra.",
  "Mình hiểu cảm giác chông chênh đó, nó là một phần bình thường của hành trình.",
  "Điều bạn vừa kể khiến mình cảm thấy bạn đang rất kiên trì.",
  "Mình nhận thấy bạn không dễ để nói ra điều này.",
  "Có lẽ điều khó nhất không phải là việc đó, mà là cảm giác phải đối mặt một mình.",
  "Mình hiểu, đôi khi mệt không phải vì việc, mà vì phải tự xoay xở mọi thứ.",
  "Điều đó nghe thật sự nặng, mình không xem nhẹ nó.",
  "Mình cảm nhận được bạn đang rất quan tâm đến kết quả này.",
  "Có vẻ bạn đang ở giữa một quyết định không dễ.",
  "Mình hiểu cảm giác đó, không cần phải vội có câu trả lời ngay.",
  "Điều bạn vừa nói cho thấy bạn đã suy nghĩ rất thấu đáo.",
  "Mình nhận thấy một chút lo âu trong câu chuyện của bạn.",
  "Có lẽ bạn đang cần được nghe rằng điều bạn cảm thấy là hợp lý.",
  "Mình hiểu, sự kỳ vọng vào bản thân đôi khi cũng là một áp lực.",
  "Điều đó nghe như bạn đã rất nỗ lực để đi đến đây.",
  "Mình cảm nhận được sự tổn thương trong những gì bạn vừa kể.",
  "Có vẻ bạn đang tự hỏi liệu mình có đang làm đúng không.",
  "Mình hiểu cảm giác hụt hẫng đó, nó hoàn toàn dễ hiểu.",
  "Điều bạn vừa chia sẻ khiến mình cảm thấy bạn không hề thờ ơ với việc này.",
  "Mình nhận thấy bạn đang cố tỏ ra ổn, nhưng có lẽ chưa hẳn vậy.",
  "Có lẽ bạn cần một người công nhận rằng điều này thật sự khó.",
  "Mình hiểu, không phải lúc nào cũng cần phải mạnh mẽ ngay lập tức.",
  "Điều đó nghe như một khoảng thời gian không dễ với bạn.",
  "Mình cảm nhận được sự kiên nhẫn trong cách bạn kể câu chuyện này.",
  "Có vẻ bạn đang cố hiểu chính cảm xúc của mình, không chỉ là vấn đề bên ngoài.",
  "Mình hiểu cảm giác cô đơn đó, dù xung quanh có nhiều người.",
  "Điều bạn vừa nói cho thấy bạn rất chân thành với chính mình.",
  "Mình nhận thấy bạn đang mang theo một sự lo lắng âm thầm.",
  "Có lẽ bạn đã giữ điều này trong lòng lâu hơn bạn nghĩ.",
  "Mình hiểu, cảm giác bất an trước điều chưa biết là điều rất con người.",
  "Điều đó nghe thật sự đáng để được lắng nghe kỹ hơn.",
  "Mình cảm nhận được bạn đang rất muốn làm điều đúng.",
  "Có vẻ bạn đang tự trách mình nhiều hơn cần thiết.",
  "Mình hiểu cảm giác áp lực phải hoàn hảo, nó không dễ buông bỏ.",
  "Điều bạn vừa kể khiến mình thấy bạn đã đi một đoạn đường không nhỏ.",
  "Mình nhận thấy có sự mâu thuẫn trong cảm xúc bạn đang trải qua.",
  "Có lẽ bạn cần thời gian để sắp xếp lại những gì đang diễn ra trong lòng.",
  "Mình hiểu, đôi khi việc thừa nhận cảm xúc khó hơn việc giải quyết vấn đề.",
  "Điều đó nghe như bạn đang đứng giữa hy vọng và lo lắng.",
  "Mình cảm nhận được sự can đảm trong việc bạn chia sẻ điều này.",
  "Có vẻ bạn vừa trải qua một điều khiến bạn phải nhìn lại nhiều thứ.",
  "Mình hiểu cảm giác mệt mỏi vì phải cố gắng liên tục.",
  "Điều bạn vừa nói khiến mình muốn hiểu bạn nhiều hơn nữa.",
  "Mình nhận thấy bạn đang rất thật với cảm xúc của mình lúc này.",
  "Có lẽ bạn không cần một câu trả lời, chỉ cần một người hiểu.",
  "Mình hiểu, không phải mọi cảm xúc đều cần có lý do rõ ràng.",
  "Điều đó nghe như một gánh nặng bạn đã mang một mình quá lâu.",
  "Mình cảm nhận được sự dịu lại trong cách bạn nói về điều này bây giờ.",
  "Có vẻ bạn đang cần được nhắc rằng cảm xúc của bạn quan trọng.",
  "Mình hiểu cảm giác bối rối giữa nhiều lựa chọn, nó không dễ chút nào.",
  "Điều bạn vừa chia sẻ cho thấy bạn đang lắng nghe chính mình rất sâu.",
  "Mình nhận thấy có một sự nhẹ nhõm nhỏ trong câu nói cuối của bạn.",
  "Có lẽ điều bạn cần nhất lúc này là biết mình không phải đang một mình.",
  "Mình hiểu, sự do dự không có nghĩa là bạn yếu đuối.",
  "Điều đó nghe như bạn đang học cách chấp nhận một điều không dễ.",
  "Mình cảm nhận được bạn đang thật sự cố gắng nhìn nhận vấn đề công bằng.",
  "Có vẻ bạn vừa nói ra một điều mà bạn đã giữ trong lòng khá lâu.",
  "Mình hiểu cảm giác áp lực thời gian, nó có thể khiến mọi thứ nặng hơn.",
  "Điều bạn vừa kể khiến mình cảm thấy được sự chân thật trong từng câu chữ.",
  "Mình nhận thấy bạn đang cố tìm một hướng đi rõ ràng hơn cho mình.",
  "Có lẽ bạn cần nghe rằng việc cảm thấy khó không có gì sai cả.",
  "Mình hiểu, đôi khi điều khó nhất là cho phép mình cảm thấy không ổn.",
  "Điều đó nghe như một bước ngoặt nhỏ trong cách bạn nhìn về việc này.",
  "Mình cảm nhận được sự ấm áp trong cách bạn kể về người khác trong câu chuyện này.",
  "Có vẻ bạn đang rất cẩn trọng với cảm xúc của những người xung quanh, và cả của chính mình.",
  "Mình hiểu cảm giác vừa nhẹ nhõm vừa lo lắng cùng một lúc.",
  "Điều bạn vừa chia sẻ giúp mình hiểu bạn hơn rất nhiều.",
];

/** Nhiệm vụ 02.3 — 100 câu hỏi gợi mở (Clarifying / Reflection). */
export const openEndedQuestions: string[] = [
  "Điều gì khiến bạn nghĩ đến việc này ngay lúc này?",
  "Nếu không có gì cản trở, bạn muốn điều gì xảy ra tiếp theo?",
  "Phần nào trong việc này khiến bạn bận tâm nhất?",
  "Bạn đã từng cảm thấy như vậy trước đây chưa?",
  "Điều gì sẽ thay đổi nếu bạn cho phép mình thử một lần?",
  "Bạn nghĩ điều gì đang thật sự đứng giữa bạn và bước tiếp theo?",
  "Nếu bạn kể cho một người bạn thân, bạn sẽ nói gì đầu tiên?",
  "Điều gì khiến bạn vẫn tiếp tục, dù mọi thứ không dễ?",
  "Bạn muốn cảm thấy thế nào sau khi vượt qua điều này?",
  "Có phần nào trong điều này bạn chưa từng nói với ai chưa?",
  "Nếu hôm nay chỉ làm được một việc nhỏ, bạn sẽ chọn việc gì?",
  "Điều gì khiến bạn tin rằng mình có thể làm được điều này?",
  "Bạn đang lo điều gì nhất khi nghĩ về bước tiếp theo?",
  "Nếu không sợ thất bại, bạn sẽ làm gì khác đi?",
  "Điều gì trong hành trình này khiến bạn tự hào nhất, dù nhỏ?",
  "Bạn nghĩ ai có thể giúp bạn lúc này, nếu có?",
  "Điều gì khiến hôm nay khác với những ngày bình thường khác?",
  "Nếu bạn có thể hỏi chính mình một câu lúc này, bạn sẽ hỏi gì?",
  "Bạn cảm thấy mình đang ở giai đoạn nào của việc này?",
  "Điều gì khiến bạn nghĩ bây giờ là thời điểm để nói ra?",
  "Bạn muốn điều gì khác đi nếu có thể quay lại đầu câu chuyện này?",
  "Có điều gì bạn đã học được từ lần trước mà vẫn áp dụng được lúc này?",
  "Điều gì sẽ khiến bạn cảm thấy nhẹ nhõm hơn ngay bây giờ?",
  "Bạn nghĩ điều gì là phần khó nhất bạn đã vượt qua tới giờ?",
  "Nếu mọi thứ diễn ra như bạn mong, bức tranh đó trông như thế nào?",
  "Điều gì khiến bạn chọn chia sẻ điều này hôm nay, không phải hôm khác?",
  "Bạn có đang so sánh mình với ai không, và điều đó có công bằng không?",
  "Điều gì bạn đang cố bảo vệ khi giữ im lặng về việc này?",
  "Nếu một người bạn đang ở vị trí của bạn, bạn sẽ nói gì với họ?",
  "Bạn nghĩ điều gì sẽ xảy ra nếu bạn không làm gì cả?",
  "Điều gì khiến bạn cảm thấy mình đã sẵn sàng, dù chỉ một chút?",
  "Bạn có để ý điều gì lặp lại trong cách bạn phản ứng với việc này?",
  "Điều gì khiến bạn nghĩ mình chưa đủ, và điều đó có thật không?",
  "Nếu được chọn lại, bạn có làm khác đi không, và khác ở điều gì?",
  "Bạn cảm thấy mình đang tiến tới điều gì, hay đang tránh điều gì?",
  "Điều gì khiến bạn tin tưởng bản thân hơn một chút lúc này?",
  "Bạn nghĩ mình cần thêm điều gì để đi tiếp — thời gian, người đồng hành, hay sự rõ ràng?",
  "Điều gì trong câu chuyện này bạn muốn được hiểu rõ hơn?",
  "Bạn có đang chờ một dấu hiệu nào đó để bắt đầu không?",
  "Điều gì khiến bạn nghĩ rằng việc này quan trọng với bạn?",
  "Nếu năm sau nhìn lại, bạn muốn mình đã làm gì hôm nay?",
  "Bạn có cảm thấy mình đang đi đúng nhịp của riêng mình không?",
  "Điều gì khiến bạn cảm thấy được là chính mình nhất?",
  "Bạn nghĩ điều gì đang giữ bạn lại, dù bạn đã sẵn sàng về lý trí?",
  "Điều gì sẽ là một bước nhỏ, không phải một bước lớn, cho việc này?",
  "Bạn có đang cố làm hài lòng ai khác hơn là chính mình không?",
  "Điều gì khiến bạn cảm thấy mình đã trưởng thành hơn so với trước đây?",
  "Bạn nghĩ điều gì đang thật sự cần được nói ra lúc này?",
  "Nếu không ai đánh giá, bạn sẽ làm gì khác?",
  "Điều gì khiến bạn cảm thấy an toàn để thử một điều mới?",
  "Bạn có nhận ra điều gì về chính mình qua câu chuyện này không?",
  "Điều gì khiến bạn nghĩ đây là lúc để dừng lại và nhìn lại?",
  "Bạn nghĩ phiên bản tốt hơn của hôm nay sẽ làm gì khác?",
  "Điều gì khiến bạn cảm thấy được ủng hộ, hay thiếu điều đó?",
  "Bạn có đang mong đợi điều gì từ chính mình mà có thể chưa công bằng?",
  "Điều gì khiến bạn vẫn giữ hy vọng, dù chỉ một chút?",
  "Bạn nghĩ điều gì sẽ giúp bạn cảm thấy ít cô đơn hơn trong việc này?",
  "Điều gì khiến bạn cảm thấy mình cần được nghỉ ngơi, hay cần được thúc đẩy?",
  "Bạn có đang đặt áp lực lên một mốc thời gian không thật sự cần thiết?",
  "Điều gì là điều bạn chưa từng cho phép mình nghĩ đến trước đây?",
  "Bạn nghĩ điều gì sẽ thay đổi nếu bạn tin mình hơn một chút?",
  "Điều gì khiến bạn cảm thấy được lắng nghe lúc này, nếu có?",
  "Bạn có đang chờ người khác cho bạn phép để bắt đầu không?",
  "Điều gì khiến bạn cảm thấy việc này đáng để cố gắng?",
  "Bạn nghĩ mình đã bỏ qua điều gì quan trọng trong lúc vội vã?",
  "Điều gì khiến bạn cảm thấy gần với mục tiêu của mình hơn?",
  "Bạn có đang nhìn nhận thất bại như một điểm kết, hay một điểm dừng tạm?",
  "Điều gì sẽ là dấu hiệu cho thấy bạn đang đi đúng hướng?",
  "Bạn nghĩ điều gì đang khiến bạn ngần ngại nói ra sự thật với chính mình?",
  "Điều gì khiến hôm nay là một ngày đáng được ghi nhớ, dù nhỏ?",
  "Bạn có đang cố làm mọi thứ một mình khi không cần phải vậy?",
  "Điều gì khiến bạn cảm thấy mình xứng đáng với điều mình mong muốn?",
  "Bạn nghĩ điều gì sẽ khiến việc này trở nên dễ chịu hơn một chút?",
  "Điều gì khiến bạn tự hỏi liệu mình có đang quá khắt khe với chính mình?",
  "Bạn có nhận ra mình đã thay đổi như thế nào so với khi bắt đầu không?",
  "Điều gì khiến bạn cảm thấy việc dừng lại lúc này là một lựa chọn, không phải một thất bại?",
  "Bạn nghĩ điều gì sẽ giúp bạn tin tưởng quá trình hơn là chỉ tin vào kết quả?",
  "Điều gì khiến bạn cảm thấy cần được ai đó công nhận lúc này?",
  "Bạn có đang lờ đi một cảm xúc nào vì nghĩ nó không quan trọng?",
  "Điều gì khiến bạn nghĩ bước tiếp theo nên nhỏ hơn là lớn?",
  "Bạn nghĩ điều gì sẽ là một dấu hiệu nhỏ cho thấy bạn đang ổn?",
  "Điều gì khiến bạn cảm thấy được kết nối với hành trình này, hay thấy xa cách với nó?",
  "Bạn có đang tự so sánh tốc độ của mình với người khác không cần thiết?",
  "Điều gì khiến bạn cảm thấy được phép nghỉ ngơi mà không thấy có lỗi?",
  "Bạn nghĩ điều gì là điều thành thật nhất bạn có thể nói với chính mình lúc này?",
  "Điều gì khiến bạn cảm thấy việc này có ý nghĩa hơn là chỉ một nhiệm vụ?",
  "Bạn có để ý mình đang nói về việc này bằng giọng điệu nào — nhẹ nhàng hay khắt khe?",
  "Điều gì khiến bạn nghĩ rằng bạn đã sẵn sàng cho một cuộc trò chuyện khó hơn về việc này?",
  "Bạn nghĩ điều gì sẽ là một lời nhắc nhẹ bạn cần nghe lúc này?",
  "Điều gì khiến bạn cảm thấy gắn bó với người, hay điều, đang được nói tới?",
  "Bạn có đang cố hoàn thành nhanh để tránh phải đối diện với một cảm xúc nào không?",
  "Điều gì khiến bạn cảm thấy việc nhìn lại hôm nay là cần thiết?",
  "Bạn nghĩ điều gì sẽ giúp bạn cảm thấy bớt áp lực hơn một chút ngay bây giờ?",
  "Điều gì khiến bạn cảm thấy mình đang lớn lên qua điều này, dù chưa thấy ngay kết quả?",
  "Bạn có đang chờ một sự hoàn hảo trước khi cho phép mình hài lòng không?",
  "Điều gì khiến bạn tin rằng câu chuyện này chưa kết thúc ở đây?",
  "Bạn nghĩ điều gì sẽ là câu trả lời thành thật nhất cho câu hỏi này, nếu không ai nghe?",
  "Điều gì khiến bạn cảm thấy việc chia sẻ điều này hôm nay là một bước tiến, không phải một sự yếu đuối?",
  "Bạn có muốn dành một chút thời gian để ngồi với cảm xúc này trước khi quyết định điều gì không?",
  "Điều gì sẽ khiến bạn cảm thấy hôm nay là một ngày đáng giữ lại, dù chỉ vì một lý do nhỏ?",
];

/** Nhiệm vụ 02.4 — 100 câu khích lệ (Guidance / Reflection). */
export const conversationalEncouragements: string[] = [
  "Bạn đã đi xa hơn bạn nghĩ, dù hôm nay cảm giác như chưa đủ.",
  "Việc bạn vẫn đang ở đây, vẫn đang cố, đã là một điều không nhỏ.",
  "Không cần phải nhanh, chỉ cần không dừng hẳn lại.",
  "Một bước nhỏ hôm nay vẫn là một bước đi tới, không phải đứng yên.",
  "Bạn không cần phải mạnh mẽ mọi lúc để được công nhận là đang cố gắng.",
  "Mỗi lần bạn quay lại sau một lúc gián đoạn, đó đã là một sự kiên trì.",
  "Bạn không cần làm đúng hết mới được phép tự hào về điều mình đã làm.",
  "Có những ngày chỉ cần giữ được nhịp đã là một thành công.",
  "Bạn đang học cách tin vào chính mình, từng chút một, và điều đó đang diễn ra.",
  "Không ai bắt đầu đã giỏi — bạn đang ở đúng giai đoạn của chính mình.",
  "Bạn không đơn độc trong việc này, dù đôi khi cảm thấy vậy.",
  "Việc bạn nhận ra điều khó, thay vì né tránh nó, đã là một bước trưởng thành.",
  "Bạn xứng đáng được nhẹ nhàng với chính mình hôm nay.",
  "Một ngày chậm hơn không xóa đi những gì bạn đã xây dựng trước đó.",
  "Bạn đang làm tốt hơn bạn tự đánh giá về mình.",
  "Không có hành trình nào đi thẳng — những lúc chững lại cũng là một phần của nó.",
  "Bạn không cần hoàn hảo, chỉ cần tiếp tục thành thật với chính mình.",
  "Mỗi lần bạn chọn không bỏ cuộc, bạn đang chứng minh điều gì đó với chính mình.",
  "Bạn đã vượt qua những ngày khó hơn hôm nay rồi.",
  "Có lẽ bạn chưa thấy kết quả, nhưng sự cố gắng đang tích lũy từng ngày.",
  "Bạn không cần ai khác xác nhận để biết mình đang tiến bộ.",
  "Việc bạn dừng lại để suy nghĩ kỹ hơn cũng là một dạng tiến triển.",
  "Bạn đang xây dựng một điều bền vững hơn là một kết quả nhanh.",
  "Không sao nếu hôm nay bạn chỉ làm được ít — ít vẫn hơn không làm gì.",
  "Bạn đang cho mình cơ hội để trưởng thành, và điều đó rất đáng quý.",
  "Một người không quan tâm sẽ không bận tâm đến mức này — bạn rõ ràng quan tâm.",
  "Bạn không cần chứng minh gì với ai cả, chỉ cần trung thực với hành trình của mình.",
  "Có những tiến bộ không nhìn thấy ngay, nhưng vẫn đang xảy ra bên trong bạn.",
  "Bạn đang làm điều không dễ, và việc bạn vẫn thử lại mỗi ngày là điều phi thường theo cách riêng.",
  "Sự kiên nhẫn bạn đang dành cho chính mình hôm nay sẽ có ý nghĩa hơn bạn tưởng.",
  "Bạn không cần phải giống ai khác để hành trình của mình có giá trị.",
  "Một quyết định nhỏ đúng lúc cũng có thể thay đổi cả một hướng đi.",
  "Bạn đang đối mặt với điều này tốt hơn bạn nghĩ.",
  "Không có gì sai khi cần thêm thời gian — thời gian không phải là kẻ thù của bạn.",
  "Bạn đang chọn tiếp tục, và đó là điều quan trọng hơn việc chọn nhanh.",
  "Có lẽ bạn chưa nhận ra, nhưng bạn đã khác đi rất nhiều so với lúc bắt đầu.",
  "Bạn không cần cảm thấy sẵn sàng 100% mới được phép bước tiếp.",
  "Việc bạn dám nói ra điều khó này đã là một dạng can đảm.",
  "Bạn đang gieo những hạt giống mà có thể chưa thấy quả ngay hôm nay.",
  "Không phải mọi nỗ lực đều cần có kết quả ngay để xứng đáng được ghi nhận.",
  "Bạn đang làm tốt việc khó nhất: tiếp tục dù chưa chắc chắn về kết quả.",
  "Một phiên bản của bạn cách đây một thời gian sẽ tự hào về những gì bạn đang làm hôm nay.",
  "Bạn không cần phải hoàn thành mọi thứ hôm nay để hôm nay có ý nghĩa.",
  "Có lẽ bước tiếp theo không cần lớn, chỉ cần là một bước thật.",
  "Bạn đang học cách lắng nghe chính mình, và đó là một kỹ năng quý giá.",
  "Sự cố gắng âm thầm của bạn vẫn đang được nhìn thấy, ít nhất là ở đây.",
  "Bạn không cần giải quyết hết mọi thứ ngay bây giờ, chỉ cần một điều tiếp theo.",
  "Có những lúc nghỉ cũng là một phần của việc tiến lên, không phải đi ngược lại.",
  "Bạn đang đối xử với chính mình tử tế hơn bạn nghĩ, qua việc dám dừng lại để hỏi.",
  "Một người không nghiêm túc với hành trình sẽ không đặt những câu hỏi như bạn đang đặt.",
  "Bạn không cần là người giỏi nhất, chỉ cần là người không bỏ cuộc với chính mình.",
  "Việc bạn vẫn giữ được sự tử tế với người khác trong lúc khó khăn của riêng mình là điều đáng quý.",
  "Bạn đang tích lũy một điều quan trọng hơn kết quả: sự hiểu chính mình.",
  "Không phải lúc nào tiến bộ cũng ồn ào — đôi khi nó rất lặng lẽ, như cách bạn đang làm.",
  "Bạn đã chọn không né tránh điều khó, và điều đó nói lên rất nhiều về bạn.",
  "Có lẽ điều bạn cần không phải thêm cố gắng, mà thêm sự tin tưởng vào chính mình.",
  "Bạn không cần phải chứng minh giá trị của mình qua tốc độ.",
  "Một ngày khó không định nghĩa cả hành trình của bạn.",
  "Bạn đang để cho mình được học, thay vì chỉ cố để đúng ngay từ đầu — đó là một sự trưởng thành.",
  "Có lẽ bạn không nhận ra, nhưng bạn đang truyền cảm hứng cho ai đó qua cách bạn kiên trì.",
  "Bạn không cần làm mọi thứ một mình, dù đôi khi cảm giác phải vậy.",
  "Sự thành thật bạn vừa thể hiện đáng giá hơn một câu trả lời hoàn hảo.",
  "Bạn đang đi đúng nhịp của mình, không cần so với nhịp của ai khác.",
  "Có những điều chỉ có thể học được qua thời gian, và bạn đang cho mình thời gian đó.",
  "Bạn không cần cảm thấy tự tin trước khi hành động — hành động đôi khi đến trước cảm giác sẵn sàng.",
  "Việc bạn quay lại sau một khoảng dừng đã chứng minh điều này thật sự quan trọng với bạn.",
  "Bạn đang cho phép mình không hoàn hảo, và đó chính là sự trưởng thành thật.",
  "Có lẽ điều bạn cần nghe hôm nay là: bạn đang làm tốt hơn bạn tự nhận.",
  "Bạn không cần một lý do lớn để tiếp tục — chỉ cần một lý do thật với bạn.",
  "Sự cố gắng của bạn không bị lãng phí, dù chưa thấy ngay kết quả.",
  "Bạn đang xây một điều có giá trị lâu dài, không chỉ một kết quả nhất thời.",
  "Có lẽ bạn đã quá khắt khe với chính mình — bạn được phép dịu lại một chút.",
  "Bạn không cần phải biết hết đường đi để bắt đầu bước tiếp theo.",
  "Việc bạn vẫn giữ hy vọng, dù nhỏ, đã là một sức mạnh đáng kể.",
  "Bạn đang chọn trưởng thành thay vì chọn dễ dàng, và điều đó không hề nhỏ.",
  "Có lẽ điều bạn vừa làm hôm nay sẽ là nền tảng cho một điều lớn hơn sau này.",
  "Bạn không cần phải vui vẻ mọi lúc để được xem là đang làm tốt.",
  "Sự kiên trì âm thầm của bạn đang được ghi nhận, ít nhất là ở đây, ngay lúc này.",
  "Bạn đang học cách đứng dậy theo cách riêng của mình, không cần giống ai.",
  "Có lẽ bạn chưa thấy, nhưng từng bước nhỏ của bạn đang cộng dồn thành một điều lớn.",
  "Bạn không cần phải chắc chắn 100% để xứng đáng được thử.",
  "Việc bạn dám đối diện với cảm xúc của mình là một phần quan trọng của sự trưởng thành.",
  "Bạn đang cho mình một cơ hội mà nhiều người không dám cho chính họ.",
  "Có lẽ điều khó nhất đã ở lại sau bạn rồi, dù bạn chưa nhận ra.",
  "Bạn không cần là phiên bản hoàn hảo của mình hôm nay, chỉ cần là một phiên bản đang cố gắng.",
  "Sự tử tế bạn đang dành cho người khác, hãy thử dành một phần cho chính mình.",
  "Bạn đang viết tiếp câu chuyện của mình theo cách không ai khác có thể viết thay.",
  "Có lẽ bạn cần nghe điều này: bạn không cần phải xứng đáng mới được nghỉ ngơi.",
  "Bạn không cần làm tất cả ngay hôm nay — chỉ cần làm điều tiếp theo, đủ tốt cho hôm nay.",
  "Việc bạn vẫn ở đây, sau tất cả, đã chứng minh một điều: bạn không dễ bỏ cuộc.",
  "Bạn đang lớn lên theo cách không phải ai cũng nhìn thấy, nhưng nó vẫn đang xảy ra.",
  "Có lẽ điều quan trọng không phải là bạn đã đi được bao xa, mà là bạn vẫn đang đi.",
  "Bạn không cần phải giỏi mọi thứ — bạn chỉ cần tiếp tục là chính mình, ngày càng rõ hơn.",
  "Sự cố gắng của bạn hôm nay là một lời cảm ơn dành cho chính bạn ở tương lai.",
  "Bạn đang chọn không bỏ rơi chính mình, và đó là điều quan trọng nhất.",
  "Có lẽ bạn cần được nhắc rằng: bạn đã đủ tốt ngay từ bây giờ, không cần chờ đến lúc hoàn thiện.",
  "Bạn không cần phải hiểu hết mọi thứ ngay — chỉ cần tiếp tục học, như bạn đang làm.",
  "Việc bạn dành thời gian này để nhìn lại chính mình đã là một dạng yêu thương bản thân.",
  "Bạn đang đi một con đường của riêng mình, và điều đó đáng được tôn trọng.",
  "Có lẽ điều bạn cần nhất lúc này chỉ là tin rằng mình đang đi đúng hướng của chính mình.",
];

/** Nhiệm vụ 02.5 — 100 câu kết thúc nhẹ nhàng (Closing). */
export const conversationClosings: string[] = [
  "Cảm ơn bạn đã chia sẻ điều này hôm nay. Khi nào bạn muốn nói tiếp, mình vẫn ở đây.",
  "Mình rất vui vì cuộc trò chuyện này. Hẹn gặp lại bạn lần sau.",
  "Hãy nhẹ nhàng với chính mình sau khi rời khỏi đây nhé.",
  "Mình sẽ ở đây, bất cứ khi nào bạn cần nói chuyện tiếp.",
  "Cảm ơn vì đã tin tưởng để kể cho mình nghe điều này.",
  "Không cần phải quyết định mọi thứ ngay hôm nay — cứ để nó lắng lại một chút.",
  "Mình mong bạn có một khoảng nghỉ dễ chịu sau cuộc trò chuyện này.",
  "Cảm ơn bạn vì đã dành thời gian này cho chính mình hôm nay.",
  "Hẹn gặp lại bạn, dù là ngày mai hay bất cứ khi nào bạn quay lại.",
  "Mình rất biết ơn vì bạn đã chia sẻ điều này cùng mình.",
  "Hãy giữ lại điều tốt nhất từ cuộc trò chuyện này, và để phần còn lại lắng xuống.",
  "Mình tin bạn sẽ tìm ra điều phù hợp nhất với mình.",
  "Cảm ơn bạn, hôm nay là một cuộc trò chuyện ý nghĩa với mình.",
  "Bất cứ khi nào bạn cần, mình vẫn ở đây để nghe tiếp.",
  "Mong bạn mang theo một chút bình yên sau những gì chúng ta vừa nói.",
  "Cảm ơn vì đã cho mình cơ hội được hiểu bạn hơn hôm nay.",
  "Hãy cho mình biết khi bạn muốn tiếp tục câu chuyện này.",
  "Mình hy vọng bạn cảm thấy nhẹ hơn một chút sau cuộc trò chuyện này.",
  "Cảm ơn bạn đã ở đây, hôm nay và những ngày trước nữa.",
  "Mong rằng những điều chúng ta vừa nói sẽ ở lại với bạn theo cách tốt đẹp.",
  "Mình rất trân trọng khoảng thời gian này cùng bạn.",
  "Hẹn gặp lại, và nhớ rằng bạn không cần phải vội điều gì cả.",
  "Cảm ơn vì đã thành thật với chính mình trong cuộc trò chuyện này.",
  "Mình mong bạn sẽ đối xử với mình tử tế trong những ngày tới.",
  "Bất cứ khi nào bạn quay lại, mình vẫn nhớ chúng ta đã nói đến đâu.",
  "Cảm ơn bạn vì cuộc trò chuyện hôm nay, nó có ý nghĩa với mình.",
  "Mong bạn giữ được sự nhẹ nhõm này một lúc, trước khi quay lại với mọi thứ khác.",
  "Mình tin rằng bạn đã mang theo một điều quý giá từ cuộc trò chuyện này.",
  "Hẹn gặp lại bạn, khi bạn sẵn sàng.",
  "Cảm ơn vì đã cho cuộc trò chuyện này một chỗ trong ngày của bạn.",
  "Mong những gì vừa nói sẽ đồng hành cùng bạn một cách nhẹ nhàng.",
  "Mình rất vui được là một phần nhỏ trong ngày hôm nay của bạn.",
  "Cảm ơn bạn, hãy chăm sóc bản thân nhé.",
  "Hẹn gặp lại, và nhớ rằng hành trình này không cần phải vội.",
  "Mình mong bạn tìm được một khoảnh khắc yên tĩnh sau cuộc trò chuyện này.",
  "Cảm ơn vì đã chia sẻ một phần của mình với mình hôm nay.",
  "Mong bạn cảm thấy được lắng nghe, ít nhất là trong khoảnh khắc này.",
  "Mình sẽ luôn ở đây khi bạn cần, không có gì phải gấp gáp.",
  "Cảm ơn bạn vì sự chân thành trong cuộc trò chuyện này.",
  "Hẹn gặp lại bạn ở một ngày khác, với một câu chuyện khác hoặc vẫn là câu chuyện này.",
  "Mong những điều tốt đẹp sẽ đến với bạn sau hôm nay.",
  "Cảm ơn vì đã để mình cùng bạn đi qua một phần của ngày hôm nay.",
  "Mình rất mong được nghe tiếp câu chuyện này vào một lúc khác.",
  "Hãy nhớ rằng bạn không cần phải mạnh mẽ ngay khi rời khỏi đây.",
  "Cảm ơn bạn vì đã ở đây cùng mình lúc này.",
  "Mong bạn mang theo sự bình thản này vào phần còn lại của ngày.",
  "Mình tin cuộc trò chuyện này đã giúp được điều gì đó, dù nhỏ.",
  "Hẹn gặp lại, và cảm ơn vì đã tin tưởng mình.",
  "Cảm ơn vì những gì bạn đã chia sẻ — mình sẽ nhớ điều đó.",
  "Mong bạn có một khoảng thời gian dễ chịu phía trước.",
  "Mình rất vui vì được đồng hành cùng bạn trong cuộc trò chuyện này.",
  "Cảm ơn bạn, hãy để mọi thứ lắng lại theo nhịp của riêng bạn.",
  "Hẹn gặp lại, dù cuộc trò chuyện tiếp theo là về điều gì.",
  "Mong rằng bạn cảm thấy ít nặng hơn so với khi bắt đầu cuộc trò chuyện này.",
  "Cảm ơn vì đã cho mình một vị trí trong câu chuyện hôm nay của bạn.",
  "Mình sẽ vẫn ở đây, dù bạn quay lại sau một giờ hay sau một tháng.",
  "Cảm ơn bạn, mong những điều vừa nói sẽ giúp bạn nhìn rõ hơn một chút.",
  "Hẹn gặp lại bạn, và nhớ rằng bạn luôn được chào đón ở đây.",
  "Mong bạn giữ được sự tử tế này cho cả chính mình, không chỉ cho người khác.",
  "Cảm ơn vì đã nói thật với mình hôm nay.",
  "Mình rất trân trọng việc bạn đã mở lòng trong cuộc trò chuyện này.",
  "Hẹn gặp lại, và nhớ rằng không có gì cần phải hoàn hảo ngay hôm nay.",
  "Cảm ơn bạn vì đã dành thời gian quý giá này cho cuộc trò chuyện.",
  "Mong bạn rời khỏi đây với một cảm giác nhẹ nhàng hơn lúc bắt đầu.",
  "Mình tin rằng bạn sẽ biết khi nào cần quay lại nói tiếp.",
  "Cảm ơn vì cuộc trò chuyện này, nó đã cho mình hiểu bạn hơn.",
  "Hẹn gặp lại, và chúc bạn một ngày bình yên phía trước.",
  "Mong những lời vừa nói sẽ ở lại với bạn như một lời nhắc nhẹ, không phải gánh nặng.",
  "Cảm ơn bạn vì đã không ngại chia sẻ điều khó này.",
  "Mình rất mong bạn cảm thấy được đồng hành, dù chỉ trong khoảnh khắc ngắn này.",
  "Hẹn gặp lại bạn, khi nào bạn thấy cần.",
  "Cảm ơn vì đã để cuộc trò chuyện này diễn ra tự nhiên, không vội vã.",
  "Mong bạn sẽ tìm thấy một chút rõ ràng hơn sau hôm nay.",
  "Mình rất vui vì đã được lắng nghe bạn hôm nay.",
  "Cảm ơn bạn, và hãy nhớ rằng bạn không cần phải có mọi câu trả lời ngay lúc này.",
  "Hẹn gặp lại, dù câu chuyện tiếp theo sẽ là gì.",
  "Mong rằng bạn cảm thấy được thấu hiểu, dù chỉ là một phần nhỏ.",
  "Cảm ơn vì đã cho mình cơ hội được ở bên bạn trong khoảnh khắc này.",
  "Mình sẽ giữ điều này lại như một phần của câu chuyện chung giữa chúng ta.",
  "Hẹn gặp lại, và cảm ơn bạn vì đã luôn cố gắng.",
  "Mong bạn có thể buông nhẹ những gì không cần mang theo nữa.",
  "Cảm ơn vì đã chọn dành cuộc trò chuyện này cho mình.",
  "Mình rất mong bạn cảm thấy ổn hơn khi rời khỏi đây.",
  "Hẹn gặp lại bạn, và nhớ rằng cánh cửa này luôn mở.",
  "Cảm ơn vì sự kiên nhẫn của bạn trong suốt cuộc trò chuyện này.",
  "Mong những điều bạn vừa nhận ra sẽ đồng hành cùng bạn một cách nhẹ nhàng.",
  "Mình rất vui được là người nghe câu chuyện của bạn hôm nay.",
  "Cảm ơn bạn, và hãy cho mình biết nếu có điều gì bạn cần thêm.",
  "Hẹn gặp lại, dù là sớm hay muộn, mình vẫn sẽ nhớ chúng ta đã nói gì.",
  "Mong bạn giữ được sự rõ ràng này một lúc lâu, trước khi mọi thứ lại bận rộn.",
  "Cảm ơn vì đã cho cuộc trò chuyện này một cơ hội diễn ra.",
  "Mình tin rằng những gì vừa chia sẻ sẽ có ý nghĩa hơn theo thời gian.",
  "Hẹn gặp lại bạn, và chúc bạn nhẹ nhàng đi qua phần còn lại của ngày hôm nay.",
  "Cảm ơn vì đã để mình hiểu thêm một phần của câu chuyện bạn.",
  "Mong bạn cảm thấy mình không hề đơn độc, ngay cả sau khi cuộc trò chuyện này kết thúc.",
  "Mình rất biết ơn cuộc trò chuyện này, và mong sẽ có nhiều cuộc trò chuyện khác như vậy.",
  "Cảm ơn bạn, và hẹn gặp lại — bất cứ khi nào bạn cần một người để nói chuyện.",
  "Mong bạn giữ được nụ cười này một chút lâu hơn, sau khi rời khỏi đây.",
  "Cảm ơn vì đã cho mình thấy một phần thật của bạn hôm nay.",
  "Hẹn gặp lại, và nhớ rằng mình luôn vui khi được nghe bạn.",
];

function pick<T>(items: T[], seed?: number): T {
  const index = seed === undefined ? Math.floor(Math.random() * items.length) : seed % items.length;
  return items[index];
}

export function getConversationOpener(seed?: number): string {
  return pick(conversationOpeners, seed);
}

export function getEmotionAcknowledgment(seed?: number): string {
  return pick(emotionAcknowledgments, seed);
}

export function getOpenEndedQuestion(seed?: number): string {
  return pick(openEndedQuestions, seed);
}

export function getConversationalEncouragement(seed?: number): string {
  return pick(conversationalEncouragements, seed);
}

export function getConversationClosing(seed?: number): string {
  return pick(conversationClosings, seed);
}

/**
 * Nhiệm vụ 03 — Context Conversation. Companion mở lời khác nhau theo
 * người đang đứng trước nó. Đây là ánh xạ V1, đơn giản theo 4 ngữ cảnh —
 * xem `docs/HUMAN_CONVERSATION_ENGINE.md`.
 */
export type ConversationContext = "newUser" | "returningUser" | "justCompleted" | "longAbsence";

export const contextualOpeners: Record<ConversationContext, string[]> = {
  newUser: [
    "Chào mừng bạn đến đây. Mình rất vui vì bạn đã bắt đầu.",
    "Chào mừng bạn. Mình là Companion, rất vui được gặp bạn lần đầu.",
  ],
  returningUser: [
    "Mình rất vui vì lại gặp bạn.",
    "Chào bạn, mình vẫn nhớ chúng ta đã nói đến đâu.",
  ],
  justCompleted: [
    "Hôm nay bạn vừa tiến thêm một bước.",
    "Mình thấy bạn vừa hoàn thành một điều — chúc mừng bạn.",
  ],
  longAbsence: [
    "Không sao cả. Chúng ta tiếp tục từ nơi mình đã dừng.",
    "Dù bao lâu bạn vắng mặt, nơi này vẫn chờ bạn.",
  ],
};

export function getContextualOpener(context: ConversationContext, seed?: number): string {
  return pick(contextualOpeners[context], seed);
}

/**
 * Nhiệm vụ 05 — Human Presence. Mỗi ngày chỉ một câu hỏi gợi mở, không
 * phải khảo sát. Cùng một ngày luôn cho cùng một câu (ổn định trong
 * ngày), đổi sang ngày khác. Không ép trả lời — đây chỉ là một lời mời.
 */
export function getDailyQuestion(date: Date = new Date()): string {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86_400_000,
  );
  return pick(openEndedQuestions, dayOfYear);
}
